### ISSUE TITLE
airvolute 1.0 board

### ISSUE THREAD

**Issue by B4njoS** [airvolute/dcs-deploy#5]
Hello!
Is it possible to install JP 5.1 on Airvolute 1.0 board? we have some 1.2 boards and more 1.0 boards..
if it is I would be happy to know how.
thanks!

**Comment by B4njoS** [comment]
By the way, i want to create a custom system image to enter the flash command and install CUDA, deepstream, docker engine and more..
thanks!

**Comment by B4njoS** [comment]
?

**Comment by B4njoS** [comment]
If nobody knows please let me know.

**Comment by jRodina** [comment]
Currently, available configurations are listed in the JSON file in the link below. Regarding the custom image, it is up to the user to install additional packages if needed.

https://github.com/airvolute/dcs-deploy/blob/main/local/config_db.json

**Comment by B4njoS** [comment]
We need to install Docker and deepstream 
We want to run a python script automatically install all the additional packages without manually install it with nvidia SDK manager

**Comment by eMrazSVK** [comment]
@B4njoS Is there any problem with docker and deepstream installation? If so, I think it is not related to the dcs-deploy as dcs-deploy prepares the sources and flashes Xavier NX device with the support for our board, but it flashes only `clean` image.

**Comment by B4njoS** [comment]
Hello
Sorry for the delay.
i want to create a custom system.img file that contains the Docker, Deepstream and all the other installations, I don't want to install the packages every time manually, i want to automate the process to be comfortable and easier

**Comment by eMrazSVK** [comment]
Okay, I consider this is not the functionality we yet support in `dcs-deploy` package. To be honest, this is not something nvidia supports out-of-the-box for all configurations. Personally, we tried to provide system img (same thing you are trying to achieve) and there were lot of issues with this. Try to look into `root filesystem`, `chroot` and other related keywords.  Take a look at our readme here https://github.com/airvolute/dcs-deploy#filesystem . We do the exact same thing, that we customize root filesystem, which is basically extracted image and the it is flashed on device. You can install packages into the `root filesystem` without the device utilizing cross compiling with the `chroot` tool. Then you can save this root filesystem and flash the device again and again and the contents will be the same in each flashed device. I do not recommend using raw images. You can read more about root filesystem here: https://docs.nvidia.com/jetson/archives/r35.3.1/DeveloperGuide/text/SD/RootFileSystem.html.

Although it's okay to share the knowledge here, I am closing this issue because it is not related to the `dcs-deploy` package itself. If you have any other issue with `dcs-deploy`, you can always open another issue.

Thank you, hope this helps.
