### ISSUE TITLE
Jetpack 5.1 deployment on Board 1.2 with Xavier

### ISSUE THREAD

**Issue by PavelGuzenfeld** [airvolute/dcs-deploy#6]
I have a problem with Aivolute 1.2 board Jetson Xavier device. After installing the jetpack according with the guide on two Board instanced then,  I've  connected 2 ,similar model USB cameras to each jetson. When I've checked the connected devices with ls /dev/ , In one Jetson instance, there are 2 /dev/video0 and /dev/video1 as there should be, but one of them does not work. On another Jetson instance, there are 4 /dev/video devices and video0 and video2 the video worked. Kindly advise.

**Comment by jRodina** [comment]
Could you give us more details regarding HW connections, what type of cameras, used drivers, etc?

**Comment by PavelGuzenfeld** [comment]
Yes, they are connected to random 2 USB ports. Nothing special. Also, same cameras worked on as expected (2 devices instead of four) on Airvolute 1.0 with Xavier jetpack 4.6. I think it would be reproducible with any USB cameras, no special drivers, just Plug and play.

**Comment by jRodina** [comment]
It is native Linux behavior to have two video devices for one physical USB camera. In your case, most probably, /dev/video0 gives you a video stream, and /dev/video1 some camera metadata. It has nothing to do with our BSP etc. There is a big difference between JP4.6 and JP5.1 due to the different versions of the kernel (Ubuntu 18.04 vs Ubuntu 20.04). Also, it is common to have USB cameras that are not plug-and-play, and you must install drivers for them (Ximea, for instance). It is good to check behavior against other Ubuntu computers. If you think it is some HW issue, please include a photo of your setup and dmesg output to see if devices are enumerated correctly.

**Comment by PavelGuzenfeld** [comment]
Thank you for our explanation and support.
